### PR TITLE
Move pippy to top level directory

### LINKED ISSUE #75: Replace box2d binaries with Box2D upstream.

### PR DESCRIPTION
**Pull request by chimosky**
Fixes #75.

@quozl kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
Can you tell me why you move `library/pippy` to `pippy`?

Will you also do this for other activities that contain `library/pippy`?

**Comment by chimosky** [comment]
I moved it because I didn't see a need for having it in `library/` as the other files in `library/` were no longer needed. I don't plan on doing this for other activities containing `library/pippy` except I have a reason to.

**Comment by quozl** [comment]
I think the move is not justified, and will make `git blame` and `git bisect` more difficult.  I agree the Box2D directories you removed are not needed.

**Comment by chimosky** [comment]
Change made, kindly review.

**Comment by quozl** [comment]
Thanks.  Tested the Graphics Physics example.

* [ ] there is an unrelated change included in the commit without explanation; it should be in a separate commit.

**Comment by chimosky** [comment]
The change was put in the commit message.

**Comment by quozl** [comment]
Yes, I know.  So what is the explanation for the unrelated change being included in the commit?  Is there some relationship between the changes that I don't understand yet?  I can't see any relationship.

**Comment by chimosky** [comment]
@quozl changes made, kindly review.

**Pull request merged**
