### PR TITLE
New Pippy logo [GCI]

### PR DESCRIPTION
**Pull request by srevinsaju**
# Proposal for new Pippy Logo 
A new Pippy logo was created as a part of GCI task. The logo was recreated to bring in the idea of learning Python through Pippy.
In comparison to the previous logo, I hope it tells a lot more on Python, Coding and Learning it :)
pippy logo by @srevinsaju

## Screenshots:
Screenshot_20191216_005754
Screenshot_20191216_005957

### Attributions:
The school server logo was committed by @tchx84 on sugar-artwork repository

License:
The new Pippy Logo is licensed under CC-BY-SA

### CODE REVIEW

**Comment by quozl** [comment]
@walterbender, @perriefidelis, please review.

Here's what it looks like on an OLPC XO-4

shot0030

shot0029

:grin: ... but that won't stop us!

**Comment by walterbender** [comment]
I like the new design -- it is a bit more playful and it definitely implies learning. The school graphic is from our school server icon, so there is some consistency with the rest of Sugar as well.

**Comment by perriefidelis** [comment]
Yes, I like the consistency it has with the rest of the icons

**Comment by srevinsaju** [comment]
Glad to know you liked it :smile:

**Comment by quozl** [comment]
@srevinsaju, did you save as plain SVG from Inkscape?  The SVG XML seems to have extra parts to it.

**Comment by srevinsaju** [comment]
No @quozl , I have sugar-iconified it. I have the original src, i can send it if necessary. The guide asked to use `sugariconify`

**Comment by quozl** [comment]
@srevinsaju, good, thanks.

**Pull request merged**
