### PR TITLE
Add max_participants = 4 in activity.info

### PR DESCRIPTION
**Pull request by AbrahmAB**
Without this property max_participant user cannot invite other users to join a shared activity
if condition in jarabe.view.buddymenu.py #L186 is not satisfied wihout this property
link --> https://goo.gl/SoqYZW

### CODE REVIEW

**Comment by walterbender** [comment]
I think the problem is in the update_invite_menu code. It should be:

if bundle_activity.get_max_participants()  == 0 or bundle_activity.get_max_participants() > 1:


That said, we should set a reasonable limit, perhaps 4.

**Comment by AbrahmAB** [comment]
On 21 June 2016 at 21:59, Walter Bender <notifications@github.com> wrote:

> I think the problem is in the update_invite_menu code. It should be:
>
> if bundle_activity.get_max_participants() == 0 or
> bundle_activity.get_max_participants() > 1:
>
> This will also let user to send invitation for activity that doesn't
support collab.
For activities without collab support just an local instance is created
without any sync with another user.
How can we identify such activities?

**Comment by walterbender** [comment]
We cannot, as far as I know. Which is why I introduced the idea of honoring the max_participations entry in activity.info. Eventually we will get this into all (most) activities. As it stands, very few support it.

**Comment by AbrahmAB** [comment]
+1 for using max_participants in activity.info
Forced push with `max_participants=4`

**Pull request merged**
