### PR TITLE
Clear only the canvas not the code. Fixes #2.

### PR DESCRIPTION
**Pull request by icarito**
I tried adding the trash can but it really doesn't feel necessary.

### CODE REVIEW

**Comment by icarito** [comment]
Comment is wront, actually fixes #44

**Comment by quozl** [comment]
Reviewed.

**Comment by quozl** [comment]
Packaged and tested.

@icarito, it would be nice if there was a way to hide the Vte; at the moment the only way to do that is to Stop and resume.

**Comment by icarito** [comment]
@quozl I didn't get your meaning. Currently the `show/hide output` toolbutton hides the vte, no?

image

**Comment by quozl** [comment]
Oh, yeah, thanks.

**Comment by quozl** [comment]
With the output panel hidden, the clear button doesn't seem to do anything.  :grin:

**Comment by icarito** [comment]
Neither does the stop button ;-)

**Comment by icarito** [comment]
@quozl while we are at it, export options are quite confusing to me, do we really want to expose `distutils` etc ?

**Comment by quozl** [comment]
No, I don't think `distutils` has much of a use-case.

**Comment by icarito** [comment]
Created a new issue for that. On the topic of clearing the editor, it already is too easy with closing the tab, and there's no undo for that... maybe merits another issue.

**Comment by quozl** [comment]
Agreed, can make two tabs, with program text, stop activity, resume activity, both tabs present, close one, and program text is destroyed.  Undo undoes typing not the tab close.

**Pull request merged**
